// Candidate data — mirrors candidates.json exactly
// In a real deployment you'd fetch this; for demo it's bundled.
export const CANDIDATES = [
  {
    member: { id: "CAND-001", name: "Sarah Johnson",    jobRole: "Senior Data Engineer",        yearsExperience: 9,  education: "MS Computer Science",               status: "COMPLETED" },
    missions: [
      { day: 7,  title: "Embeddings Explained",                  passed: true,  attempts: 1 },
      { day: 8,  title: "Vector Databases Overview",             passed: true,  attempts: 1 },
      { day: 10, title: "Retrieval & Matching Engine",           passed: true,  attempts: 2 },
      { day: 12, title: "Prompt Engineering Fundamentals",       passed: true,  attempts: 4 },
      { day: 16, title: "Chatbot Backend & API Integration",     passed: true,  attempts: 1 },
      { day: 22, title: "Multi-Agent Orchestration",             passed: true,  attempts: 2 },
      { day: 23, title: "Model Context Protocol (MCP)",          passed: true,  attempts: 2 },
      { day: 28, title: "Docker & Kubernetes Deployment",        passed: true,  attempts: 3 },
      { day: 29, title: "Monitoring, Logging & Observability",   skipped: true },
      { day: 31, title: "Capstone Project & Final Demo",         passed: true,  attempts: 1 },
    ],
    signals: { commitDays: 28, missionsCompleted: 30, missionsFirstTry: 20 },
  },
  {
    member: { id: "CAND-003", name: "Emily Chen",        jobRole: "AI Engineer",                yearsExperience: 6,  education: "MS Artificial Intelligence",         status: "COMPLETED" },
    missions: [
      { day: 7,  title: "Embeddings Explained",                  passed: true, attempts: 1 },
      { day: 8,  title: "Vector Databases Overview",             passed: true, attempts: 1 },
      { day: 10, title: "Retrieval & Matching Engine",           passed: true, attempts: 1 },
      { day: 11, title: "RAG End-to-End & LLM API Basics",      passed: true, attempts: 1 },
      { day: 12, title: "Prompt Engineering Fundamentals",       passed: true, attempts: 1 },
      { day: 13, title: "Function Calling & Structured Outputs", passed: true, attempts: 1 },
      { day: 21, title: "LangChain Agents",                      passed: true, attempts: 1 },
      { day: 22, title: "Multi-Agent Orchestration",             passed: true, attempts: 1 },
      { day: 23, title: "Model Context Protocol (MCP)",          passed: true, attempts: 1 },
      { day: 31, title: "Capstone Project & Final Demo",         passed: true, attempts: 1 },
    ],
    signals: { commitDays: 31, missionsCompleted: 31, missionsFirstTry: 30 },
  },
  {
    member: { id: "CAND-006", name: "Wendy Foster",     jobRole: "Marketing Manager",           yearsExperience: 12, education: "BA Marketing",                      status: "COMPLETED" },
    missions: [
      { day: 1,  title: "VS Code & Python Environment Setup",    passed: true,  attempts: 3 },
      { day: 7,  title: "Embeddings Explained",                  passed: true,  attempts: 5 },
      { day: 8,  title: "Vector Databases Overview",             passed: true,  attempts: 5 },
      { day: 12, title: "Prompt Engineering Fundamentals",       passed: true,  attempts: 4 },
      { day: 16, title: "Chatbot Backend & API Integration",     passed: true,  attempts: 4 },
      { day: 17, title: "Chatbot Frontend Development",          passed: true,  attempts: 2 },
      { day: 22, title: "Multi-Agent Orchestration",             passed: true,  attempts: 5 },
      { day: 27, title: "Security, Privacy & Guardrails",        skipped: true },
      { day: 28, title: "Docker & Kubernetes Deployment",        skipped: true },
      { day: 31, title: "Capstone Project & Final Demo",         passed: true,  attempts: 3 },
    ],
    signals: { commitDays: 19, missionsCompleted: 24, missionsFirstTry: 2 },
  },
  {
    member: { id: "CAND-010", name: "Gerald Combs",     jobRole: "IT Support Specialist",       yearsExperience: 20, education: "AAS Information Technology",         status: "COMPLETED" },
    missions: [
      { day: 1,  title: "VS Code & Python Environment Setup",    passed: true,  attempts: 2 },
      { day: 7,  title: "Embeddings Explained",                  passed: true,  attempts: 5 },
      { day: 8,  title: "Vector Databases Overview",             passed: false, attempts: 4 },
      { day: 10, title: "Retrieval & Matching Engine",           passed: false, attempts: 3 },
      { day: 12, title: "Prompt Engineering Fundamentals",       passed: true,  attempts: 5 },
      { day: 16, title: "Chatbot Backend & API Integration",     passed: true,  attempts: 4 },
      { day: 22, title: "Multi-Agent Orchestration",             passed: false, attempts: 3 },
      { day: 27, title: "Security, Privacy & Guardrails",        skipped: true },
      { day: 28, title: "Docker & Kubernetes Deployment",        skipped: true },
      { day: 31, title: "Capstone Project & Final Demo",         passed: true,  attempts: 3 },
    ],
    signals: { commitDays: 22, missionsCompleted: 23, missionsFirstTry: 1 },
  },
  {
    member: { id: "CAND-015", name: "Noah Kim",          jobRole: "Principal Architect",         yearsExperience: 20, education: "MS Computer Science",               status: "COMPLETED" },
    missions: [
      { day: 1,  title: "VS Code & Python Environment Setup",    passed: true,  attempts: 1 },
      { day: 7,  title: "Embeddings Explained",                  passed: true,  attempts: 1 },
      { day: 8,  title: "Vector Databases Overview",             passed: true,  attempts: 1 },
      { day: 14, title: "Fine-Tuning: Concepts & When to Use It", skipped: true },
      { day: 15, title: "Fine-Tuning: Hands-On with LoRA & QLoRA", skipped: true },
      { day: 21, title: "LangChain Agents",                      passed: true,  attempts: 1 },
      { day: 22, title: "Multi-Agent Orchestration",             passed: true,  attempts: 1 },
      { day: 23, title: "Model Context Protocol (MCP)",          passed: true,  attempts: 1 },
      { day: 27, title: "Security, Privacy & Guardrails",        passed: true,  attempts: 1 },
      { day: 31, title: "Capstone Project & Final Demo",         passed: true,  attempts: 1 },
    ],
    signals: { commitDays: 29, missionsCompleted: 29, missionsFirstTry: 27 },
  },
  {
    member: { id: "CAND-018", name: "Diane Foster",     jobRole: "AI Engineer",                 yearsExperience: 4,  education: "MS Computer Science",               status: "COMPLETED" },
    missions: [
      { day: 7,  title: "Embeddings Explained",                  passed: true, attempts: 1 },
      { day: 8,  title: "Vector Databases Overview",             passed: true, attempts: 1 },
      { day: 10, title: "Retrieval & Matching Engine",           passed: true, attempts: 1 },
      { day: 12, title: "Prompt Engineering Fundamentals",       passed: true, attempts: 1 },
      { day: 13, title: "Function Calling & Structured Outputs", passed: true, attempts: 1 },
      { day: 22, title: "Multi-Agent Orchestration",             passed: true, attempts: 1 },
      { day: 23, title: "Model Context Protocol (MCP)",          passed: true, attempts: 1 },
      { day: 27, title: "Security, Privacy & Guardrails",        passed: true, attempts: 1 },
      { day: 28, title: "Docker & Kubernetes Deployment",        passed: true, attempts: 1 },
      { day: 31, title: "Capstone Project & Final Demo",         passed: true, attempts: 1 },
    ],
    signals: { commitDays: 31, missionsCompleted: 31, missionsFirstTry: 31 },
  },
];

export type Candidate = (typeof CANDIDATES)[0];
